# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SblItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('network', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сеть')),
                ('ref_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ref')),
                ('domen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Домен')),
                ('ref_href', models.CharField(blank=True, max_length=100, null=True, verbose_name='Детальная ссылка')),
                ('ptext', models.TextField(blank=True, max_length=300, null=True, verbose_name='Короткий текст')),
                ('ref_detail_text', models.TextField(blank=True, null=True, verbose_name='Детальный текст')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'SBL item',
                'verbose_name': 'SBL item',
            },
        ),
        migrations.CreateModel(
            name='SblLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Лог',
                'verbose_name': 'Лог',
            },
        ),
    ]
